/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package friends_notes_system;

import static friends_notes_system.StudentOPFrame.studentname;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;

/**
 *
 * @author HP
 */
public class DownloadDataHistory extends javax.swing.JFrame {

    /**
     * Creates new form DownloadDataHistory
     */
    public DownloadDataHistory() {
        super(studentname+",Notes Downloaded History ...");
        initComponents();
        ArrayList data=new DownloadData().getDownloadInfo(studentname);
        String [] columnname={"File Name","Upload user name","Date & Time"};
        String[][] tabledata=new String[data.size()][3];
        
        for (int i = 0; i < data.size(); i++) {
            ArrayList row=(ArrayList) data.get(i);
            tabledata[i][0]=(String) row.get(0).toString();
            tabledata[i][1]=(String) row.get(1).toString();
            tabledata[i][2]=(String) row.get(2).toString();
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(tabledata,columnname));
        
        jMenuBar5.setBackground(new Color(0, 74, 124));
        jMenuBar5.setForeground(Color.WHITE);

        jMenu6.setBackground(new Color(0, 74, 124));
        jMenu6.setForeground(Color.WHITE);
        jMenu7.setBackground(new Color(0, 74, 124));
        jMenu7.setForeground(Color.WHITE);
        jMenu8.setBackground(new Color(0, 74, 124));
        jMenu8.setForeground(Color.WHITE);
        jMenu5.setBackground(new Color(0, 74, 124));
        jMenu5.setForeground(Color.WHITE);

        jMenuItem1.setBackground(new Color(0, 74, 124));
        jMenuItem1.setForeground(Color.WHITE);
        jMenuItem8.setBackground(new Color(0, 74, 124));
        jMenuItem8.setForeground(Color.WHITE);
         jMenuItem9.setBackground(new Color(0, 74, 124));
        jMenuItem9.setForeground(Color.WHITE);
         jMenuItem6.setBackground(new Color(0, 74, 124));
        jMenuItem6.setForeground(Color.WHITE);
         jMenuItem10.setBackground(new Color(0, 74, 124));
        jMenuItem10.setForeground(Color.WHITE);
         jMenuItem7.setBackground(new Color(0, 74, 124));
        jMenuItem7.setForeground(Color.WHITE);
        jTable1.setOpaque(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(770, 121, 940, 740);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download history frame.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 2030, 1020);

        jMenu5.setBackground(new java.awt.Color(0, 74, 124));
        jMenu5.setForeground(new java.awt.Color(255, 255, 255));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Manage Profile logo.png"))); // NOI18N
        jMenu5.setText("Manage Profile");

        jMenuItem6.setBackground(new java.awt.Color(55, 111, 148));
        jMenuItem6.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit Profile logo.png"))); // NOI18N
        jMenuItem6.setText("Edit Profile");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem6);

        jMenuBar5.add(jMenu5);

        jMenu6.setBackground(new java.awt.Color(0, 74, 124));
        jMenu6.setForeground(new java.awt.Color(255, 255, 255));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload logo.png"))); // NOI18N
        jMenu6.setText("Upload");

        jMenuItem7.setBackground(new java.awt.Color(55, 111, 148));
        jMenuItem7.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/upload data logo.png"))); // NOI18N
        jMenuItem7.setText("Upload Notes");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem8.setBackground(new java.awt.Color(55, 111, 148));
        jMenuItem8.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/view or edit logo.png"))); // NOI18N
        jMenuItem8.setText("View / Edit");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuBar5.add(jMenu6);

        jMenu7.setBackground(new java.awt.Color(0, 74, 124));
        jMenu7.setForeground(new java.awt.Color(255, 255, 255));
        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download logo.png"))); // NOI18N
        jMenu7.setText("Download");
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jMenuItem1.setBackground(new java.awt.Color(55, 111, 148));
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download data logo.png"))); // NOI18N
        jMenuItem1.setText("Download Data");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuItem9.setBackground(new java.awt.Color(55, 111, 148));
        jMenuItem9.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/download history logo.png"))); // NOI18N
        jMenuItem9.setText("Download History");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuBar5.add(jMenu7);

        jMenu8.setBackground(new java.awt.Color(0, 74, 124));
        jMenu8.setForeground(new java.awt.Color(255, 255, 255));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout logo.png"))); // NOI18N
        jMenu8.setText("Logout");

        jMenuItem10.setBackground(new java.awt.Color(55, 111, 148));
        jMenuItem10.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout logo.png"))); // NOI18N
        jMenuItem10.setText("Logout");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        jMenuBar5.add(jMenu8);

        setJMenuBar(jMenuBar5);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        StudentEditFrame sef=new StudentEditFrame();
        sef.setVisible(true);
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        sef.setSize(d);

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UploadFrame uf=new UploadFrame();
        uf.setVisible(true);
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        uf.setSize(d);

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        UploaaViewEditFrame uvef=new UploaaViewEditFrame();
        uvef.setVisible(true);
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        uvef.setSize(d);

    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DownloadFrame df=new DownloadFrame();
        df.setVisible(true);
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        df.setSize(d);

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DownloadDataHistory ddf=new DownloadDataHistory();
        ddf.setVisible(true);
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        ddf.setSize(d);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        LoginFrame f1=new LoginFrame();
        f1.setVisible(true);
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        f1.setSize(d);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DownloadDataHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DownloadDataHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DownloadDataHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DownloadDataHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DownloadDataHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
